global_config:
  log:
    level: 0
    path: ./dns_updater.log
    max_size: 10
    max_backups: 5
    max_age: 7
    compress: true
lists:
  - env: cloudDNS
    timeout: 30
    cloudDNS:
      credential: credential.json
      project_id: projectID
      zone_name: zoneName
      name: name
      record_type: A
  - env: mydns
    tiemout: 30
    mydns:
      username: mydns111222
      password: passwdpasswd
  - env: googleDomain
    tiemout: 30
    google_domain:
      name: domain
      username: userName
      password: passwdpasswd
